
export interface ApiColumnSchema {
    name: string;          
    type: string;          
    isPrimaryKey: boolean; 
    isNullable: boolean;   
    isForeignKey: boolean; 
    isAutoGenerated?: boolean; 
  }
  
  export interface ApiFetchDataResponse {
    data: any[];   
    total: number; 
  }
  
  export interface NewColumnPayload {
    name: string;        
    type: string;        
    isNullable?: boolean; 
    defaultValue?: any; 
    isUnique?: boolean;   
    
  }


  export interface LoginCredentials {
    email: string;
    password: string;
  }
  

  export interface SignupCredentials {
    username: string;
    email: string;
    password: string;
  }

  export interface LoggedInUser {
    user_id: BigInt;
    username: string; 
    email: string;
  }

  export interface FilterCondition{
  id: number; 
  column?: string;
  operator?: string;
  value?: any;
  logicalOperator?: 'AND' | 'OR'; 
  }

  
export interface ApiDatabase {
  user_id: number;
  db_id: number;
  db_name: string;
}

export interface ApiTableInfo {
  table_id: number;
  table_name: string;
  
}

export interface AddTableResponse {
  message: string;
  table: ApiTableInfo & { user_id: number; db_id: number }; 
  physicalName?: string;
}


export interface RenameTableResponse {
   message: string;
   table: ApiTableInfo & { user_id: number; db_id: number };
}


export interface AddDatabaseResponse {
   message: string;
   database: ApiDatabase;
}


export interface RenameDatabaseResponse {
   message: string;
   database: ApiDatabase;
}